baseURL = "http://thesimpleengineer.github.io/"
languageCode = "en-us"
title = "My Blog"
theme = "contrast-hugo"

[params]
  disqusShortname = "your-disqus-shortname"  # Add this line with your Disqus shortname
